apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-test-app-servicemonitor
  namespace: monitoring     # namespace Prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: my-test-app
  namespaceSelector:
    matchNames:
      - default             # le namespace où est exposé ton Service
  endpoints:
    - port: metrics
      interval: 15s

