apiVersion: v1
kind: Service
metadata:
  name: my-test-app-metrics
  namespace: default       # namespace de ton app
  labels:
    app: my-test-app
spec:
  ports:
    - name: metrics
      port: 3000
      targetPort: 3000
  selector:
    app: my-test-app

