replicaCount: 3
image:
  repository: registry.gitlab.com/grouptest2480246/my-test-app
  tag: e86f1bda
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 3000
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
env:
  - name: NODE_ENV
    value: "production"
