replicaCount: 1

image:
  repository: registry.gitlab.com/grouptest2480246/my-test-app
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: NODE_ENV
    value: "development"
