replicaCount: 2
image:
  repository: registry.gitlab.com/grouptest2480246/my-test-app
  tag: "7f6922a6"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 3000
resources:
  limits:
    cpu: 300m
    memory: 300Mi
  requests:
    cpu: 150m
    memory: 150Mi
env:
  - name: NODE_ENV
    value: "test"
