apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahimbakayoko/SecureGitOpsLab.git
    targetRevision: HEAD
    path: argocd/helm-deploy/overlays/chart
    helm:
      valueFiles:
        - ../dev/dev-values.yaml  # Chemin relatif au dossier "path"
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
