# Namespace ArgoCD
apiVersion: v1
kind: Namespace
metadata:
  name: argocd

---
# ArgoCD Installation (source officielle)
# Version : stable (tu peux fixer la version si besoin)
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: argocd-server
      namespace: argocd
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: argocd-server-role
      namespace: argocd
    rules:
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "list", "watch"]
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: argocd-server-binding
      namespace: argocd
    roleRef:
      kind: Role
      name: argocd-server-role
      apiGroup: rbac.authorization.k8s.io
    subjects:
      - kind: ServiceAccount
        name: argocd-server
        namespace: argocd

---
# Manifests officiels ArgoCD
# Source: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# Mais collé ici pour que tu gardes tout dans ton repo

# (Tu peux aussi juste pointer avec cette ligne si tu préfères : 👇)
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

# Pour garder le fichier ici : télécharge et colle le contenu complet de
# https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# ou utilise wget :
# wget https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml -O argocd/install.yaml
