apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-test-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-test-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-test-app.name" . }}
    spec:
      containers:
        - name: {{ include "my-test-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
